# Generated by Django 5.0.1 on 2026-02-25 15:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='analyst', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('account_id_raw', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('source', models.CharField(default='demo', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('composite_score', models.IntegerField(null=True)),
                ('risk_band', models.CharField(blank=True, max_length=50)),
                ('capital_implication', models.CharField(blank=True, max_length=20)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('duration_seconds', models.FloatField(null=True)),
                ('extraction_stats', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('full_result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.googleadsaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_token', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('refresh_token', models.TextField()),
                ('mcc_id', models.CharField(blank=True, max_length=20)),
                ('api_version', models.CharField(default='v23', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='googleadsaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_accounts', to='core.organization'),
        ),
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('max_audits_per_month', models.IntegerField(default=10)),
                ('max_accounts', models.IntegerField(default=5)),
                ('max_users', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('prefix', models.CharField(max_length=8)),
                ('scopes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedFlagRule',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('domain', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_flag_rules', to='core.organization')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditRedFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rule_id_raw', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('triggered_by', models.CharField(max_length=300)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flags', to='core.audit')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_instances', to='core.redflagrule')),
            ],
            options={
                'ordering': ['-severity', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_capture_weight', models.FloatField(default=0.25)),
                ('automation_exposure_weight', models.FloatField(default=0.2)),
                ('measurement_integrity_weight', models.FloatField(default=0.25)),
                ('capital_allocation_weight', models.FloatField(default=0.2)),
                ('creative_velocity_weight', models.FloatField(default=0.1)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('report_title', models.CharField(default='Media Operations Integrity Report', max_length=200)),
                ('footer_text', models.CharField(default='CONFIDENTIAL', max_length=500)),
                ('page_size', models.CharField(default='A4', max_length=10)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_config', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditDomainScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('demand_capture_integrity', 'Demand Capture'), ('automation_exposure', 'Automation Exposure'), ('measurement_integrity', 'Measurement Integrity'), ('capital_allocation_discipline', 'Capital Allocation'), ('creative_velocity', 'Creative Velocity')], max_length=50)),
                ('value', models.IntegerField()),
                ('weight', models.FloatField()),
                ('weighted_contribution', models.FloatField()),
                ('data_completeness', models.FloatField(default=1.0)),
                ('key_findings', models.JSONField(default=list)),
                ('sub_scores', models.JSONField(default=dict)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_scores', to='core.audit')),
            ],
            options={
                'ordering': ['domain'],
                'unique_together': {('audit', 'domain')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='googleadsaccount',
            unique_together={('organization', 'account_id')},
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('pdf', 'PDF Report'), ('html', 'HTML Report'), ('xlsx', 'Excel Report'), ('json', 'Scorecard JSON'), ('zip', 'Evidence Pack')], max_length=10)),
                ('file', models.FileField(upload_to='reports/%Y/%m/')),
                ('file_size', models.IntegerField(default=0)),
                ('file_name', models.CharField(max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.audit')),
            ],
            options={
                'ordering': ['report_type', '-version'],
                'unique_together': {('audit', 'report_type', 'version')},
            },
        ),
    ]
