# Generated by Django 5.0.1 on 2026-02-25 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_simplify_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('report_title', models.CharField(default='Media Operations Integrity Report', max_length=200)),
                ('footer_text', models.CharField(default='CONFIDENTIAL', max_length=500)),
                ('page_size', models.CharField(default='A4', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
