# Generated by Django 5.0.1 on 2026-02-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_report_config_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadscredential',
            name='account_sync_interval_hours',
            field=models.PositiveIntegerField(default=6, help_text='How often to sync accounts from Google Ads (in hours)'),
        ),
    ]
