# Generated by Django 5.0.1 on 2026-02-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_account_sync_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_ads_accounts',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.googleadsaccount'),
        ),
    ]
