# Generated by Django 5.0.1 on 2026-03-03 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_google_ads_accounts_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadscredential',
            name='oauth_scopes',
            field=models.TextField(blank=True, default='', help_text='Space-separated OAuth2 scopes granted by the current refresh token'),
        ),
        migrations.CreateModel(
            name='GA4Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('property_id', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=200)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('industry_category', models.CharField(blank=True, max_length=100)),
                ('service_level', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('bq_project_id', models.CharField(blank=True, max_length=100)),
                ('bq_dataset_id', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_properties', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'property_id')},
            },
        ),
        migrations.AddField(
            model_name='googleadsaccount',
            name='ga4_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_ads_accounts', to='core.ga4property'),
        ),
    ]
