# Generated by Django 5.0.1 on 2026-03-03 17:07

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Audit = apps.get_model("core", "Audit")
    seen = set()
    for audit in Audit.objects.all().order_by("created_at"):
        date_str = str(audit.date_range_start) if audit.date_range_start else "draft"
        base = slugify(f"{audit.account_name}-{date_str}")
        if not base:
            base = "audit"
        base = base[:100]
        candidate = base
        counter = 1
        while candidate in seen:
            candidate = f"{base}-{counter}"
            counter += 1
        seen.add(candidate)
        audit.slug = candidate
        audit.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ga4_property_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='slug',
            field=models.SlugField(blank=True, default="", max_length=120),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='audit',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
